# Generated by Django 3.1.2 on 2020-11-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='brand',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='category',
            field=models.ManyToManyField(to='substitute.Category'),
        ),
        migrations.AddField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='nutriscore',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='purchase_places',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='store',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historic',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliment', to='substitute.aliment'),
        ),
        migrations.AddField(
            model_name='historic',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute', to='substitute.aliment'),
        ),
        migrations.AddField(
            model_name='historic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='substitute.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
