# Generated by Django 3.1.2 on 2020-11-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_auto_20201106_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='substitute.category'),
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='substitute.aliment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='substitute.users')),
            ],
        ),
    ]
