# Generated by Django 3.1.2 on 2020-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_auto_20201110_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='category',
        ),
        migrations.AddField(
            model_name='aliment',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
