# Generated by Django 3.1.2 on 2020-11-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_auto_20201111_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='tag',
            field=models.ManyToManyField(to='substitute.Tag'),
        ),
    ]
