# Generated by Django 3.1.2 on 2020-11-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20201111_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fk_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_name', to='substitute.tag'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment', to='substitute.aliment'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='substitute.aliment'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='substitute.users'),
        ),
    ]
