# Generated by Django 3.1.2 on 2020-11-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0007_auto_20201111_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
