# Generated by Django 3.1.2 on 2020-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0009_aliment_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='energy_kcal',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='energy_kcal_unit',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='energy_kj',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='energy_kj_unit',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='image_nutriments',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
