# Generated by Django 3.1.2 on 2020-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0010_auto_20201120_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='energy_kcal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='energy_kcal_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='energy_kj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='energy_kj_unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
