# Generated by Django 3.1.2 on 2020-11-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0012_auto_20201120_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
