# Generated by Django 3.1.2 on 2020-11-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0015_auto_20201123_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
