# Generated by Django 3.1.2 on 2020-12-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0017_auto_20201123_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, null=True)),
                ('footer', models.CharField(max_length=1000, null=True)),
                ('home', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
