# Generated by Django 3.1.2 on 2020-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0018_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='footer',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='home',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
